"""empty message

Revision ID: dfd5332c26c0
Revises: 60e1886422d8
Create Date: 2020-04-07 21:00:16.330981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd5332c26c0'
down_revision = '60e1886422d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'available_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('available_hours', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
